export enum RESOURCES_ACTION_TYPES {
  CHANGE_SEARCH_QUERY = "CHANGE_SEARCH_QUERY",
  SET_SORTING = "SET_SORTING",
  GET_RESOURCES = "GET_RESOURCES",
  GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS",
  GET_RESOURCES_FAILED = "GET_RESOURCES_FAILED",
}
